server:
  port: 7001
eureka:
  server:
    #eureka 关闭自我保护机制
    #enable-self-preservation: false
  instance:
    #eureka服务端的实例名字
    hostname: localhost
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责是维护服务实例,并不去检索服务
    fetch-registry: false
    service-url:
      #设置eureka的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/